#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangfire.Dashboard.Pages
{
    using System;
    
    #line 2 "..\..\Dashboard\Pages\EnqueuedJobsPage.cshtml"
    using System.Collections;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Dashboard\Pages\EnqueuedJobsPage.cshtml"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    using System.Linq;
    using System.Text;
    
    #line 4 "..\..\Dashboard\Pages\EnqueuedJobsPage.cshtml"
    using Hangfire.Dashboard;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Dashboard\Pages\EnqueuedJobsPage.cshtml"
    using Hangfire.Dashboard.Pages;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class EnqueuedJobsPage : RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");







            
            #line 7 "..\..\Dashboard\Pages\EnqueuedJobsPage.cshtml"
  
    Layout = new LayoutPage(Queue.ToUpperInvariant());

    int from, perPage;

    int.TryParse(Query("from"), out from);
    int.TryParse(Query("count"), out perPage);
    string filterString = Query("filterString");
    string filterMethodString = Query("filterMethodString");
    string startDate = Query("startDate");
    string endDate = Query("endDate");
    string startTime = Query("startTime");
    string endTime = Query("endTime");

    var monitor = Storage.GetMonitoringApi();
    var countParameters = new Dictionary<string, string>()
    {
        { "filterString", filterString },
        { "filterMethodString", filterMethodString },
        { "startDate", startDate },
        { "endDate", endDate },
        { "startTime", startTime },
        { "endTime", endTime }
    };

    var jobCount = monitor.EnqueuedCount(Queue, countParameters);
    var pager = new Pager(from, perPage, jobCount)
    {
        JobsFilterText = filterString,
        JobsFilterMethodText = filterMethodString,
        JobsFilterStartDate = startDate,
        JobsFilterEndDate = endDate,
        JobsFilterStartTime = startTime,
        JobsFilterEndTime = endTime
    };
    var enqueuedJobs = monitor.EnqueuedJobs(Queue, pager);


            
            #line default
            #line hidden
WriteLiteral("\r\n<div class=\"row\">\r\n    <div class=\"col-md-3\">\r\n        ");


            
            #line 47 "..\..\Dashboard\Pages\EnqueuedJobsPage.cshtml"
   Write(Html.JobsSidebar());

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <div class=\"col-md-9\">\r\n        ");


            
            #line 50 "..\..\Dashboard\Pages\EnqueuedJobsPage.cshtml"
   Write(Html.Breadcrumbs(Queue.ToUpperInvariant(), new Dictionary<string, string>
        {
            { "Queues", Url.LinkToQueues() }
        }));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n        <h1 class=\"page-header\">");


            
            #line 55 "..\..\Dashboard\Pages\EnqueuedJobsPage.cshtml"
                           Write(Queue.ToUpperInvariant());

            
            #line default
            #line hidden
WriteLiteral(" <small>Enqueued jobs</small></h1>\r\n\r\n");


            
            #line 57 "..\..\Dashboard\Pages\EnqueuedJobsPage.cshtml"
         if (pager.TotalPageCount == 0)
        {

            
            #line default
            #line hidden
WriteLiteral("            <div class=\"alert alert-info\">\r\n                The queue is empty.\r\n" +
"            </div>\r\n");


            
            #line 62 "..\..\Dashboard\Pages\EnqueuedJobsPage.cshtml"
        }
        else
        {

            
            #line default
            #line hidden
WriteLiteral("            <div class=\"js-jobs-list\">\r\n                <div class=\"btn-toolbar b" +
"tn-toolbar-top\">\r\n                    <button class=\"js-jobs-list-command btn bt" +
"n-sm btn-default\"\r\n                            data-url=\"");


            
            #line 68 "..\..\Dashboard\Pages\EnqueuedJobsPage.cshtml"
                                 Write(Url.To("/jobs/enqueued/delete"));

            
            #line default
            #line hidden
WriteLiteral(@"""
                            data-loading-text=""Deleting...""
                            data-confirm=""Do you really want to DELETE ALL selected jobs?""
                            disabled=""disabled"">
                        <span class=""glyphicon glyphicon-remove""></span>
                        Delete selected
                    </button>
");


            
            #line 75 "..\..\Dashboard\Pages\EnqueuedJobsPage.cshtml"
                     if (EnableSearch == true)
                    {
            
            #line default
            #line hidden
WriteLiteral(" <button data-toggle=\"collapse\" data-target=\"#advanced-search-bar\" class=\"btn btn" +
"-sm btn-success\">Advanced Search</button> ");


            
            #line 76 "..\..\Dashboard\Pages\EnqueuedJobsPage.cshtml"
                                                                                                                                                }

            
            #line default
            #line hidden
WriteLiteral("                </div>\r\n");


            
            #line 78 "..\..\Dashboard\Pages\EnqueuedJobsPage.cshtml"
                 if (EnableSearch == true)
                {

            
            #line default
            #line hidden
WriteLiteral(@"                    <div id=""advanced-search-bar"" class=""collapse well"">
                        <h4 class=""advanced-search-header"">
                            Advanced Search
                        </h4>
                        <div class=""row"">
                            <div class=""col-md-12"">
                                <div class=""form-group"">
                                    <input type=""text"" value="""" id=""filterValueString"" class=""form-control"" placeholder=""Search..."" />
                                </div>
                                <div class=""form-group"">
");


            
            #line 90 "..\..\Dashboard\Pages\EnqueuedJobsPage.cshtml"
                                      
                                        var currentDateTime = DateTime.Now.ToString("dd/MM/yyyy HH:mm");
                                    

            
            #line default
            #line hidden
WriteLiteral(@"                                    <input id=""filterOnDateTime"" name=""filterOnDateTime"" type=""checkbox"" class=""js-jobs-filterOnDateTime-checked"" />
                                    <label for=""filterOnDateTime"">Filter on date time</label>
                                    <div id=""datetime-filters"" class=""row"">
                                        <div class=""col-xs-6"">
                                            <input type=""text"" value=""");


            
            #line 97 "..\..\Dashboard\Pages\EnqueuedJobsPage.cshtml"
                                                                 Write(currentDateTime);

            
            #line default
            #line hidden
WriteLiteral("\" class=\"datetimeselector-start form-control\" id=\"startDateTime\" />\r\n            " +
"                            </div>\r\n                                        <div" +
" class=\"col-xs-6\">\r\n                                            <input type=\"tex" +
"t\" value=\"");


            
            #line 100 "..\..\Dashboard\Pages\EnqueuedJobsPage.cshtml"
                                                                 Write(currentDateTime);

            
            #line default
            #line hidden
WriteLiteral(@""" class=""datetimeselector-end form-control"" id=""endDateTime"" />
                                        </div>
                                    </div>
                                </div>
                                <div class=""form-group"">
                                    <input id=""filterOnMethodName"" name=""filterOnMethodName"" type=""checkbox"" class=""js-jobs-filterOnMethodName-checked"" />
                                    <label for=""filterOnMethodName"">Filter on method name</label>
                                    <input type=""text"" value="""" id=""filterMethodString"" class=""form-control"" placeholder=""Method name..."" />
                                </div>
                            </div>
                        </div>
                        <div class=""row"">
                            <div class=""col-md-12"">
                                <button class=""js-jobs-filter-command btn btn-sm btn-success"" data-url=""");


            
            #line 113 "..\..\Dashboard\Pages\EnqueuedJobsPage.cshtml"
                                                                                                   Write(Url.To("/jobs/enqueued"));

            
            #line default
            #line hidden
WriteLiteral(@""" >
                                <span class=""glyphicon glyphicon-repeat""></span>
                                    Filter jobs
                                </button>
                            </div>
                        </div>
                    </div>
");


            
            #line 120 "..\..\Dashboard\Pages\EnqueuedJobsPage.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                ");


            
            #line 121 "..\..\Dashboard\Pages\EnqueuedJobsPage.cshtml"
           Write(Html.PerPageSelector(pager));

            
            #line default
            #line hidden
WriteLiteral(@"
                <table class=""table"">
                    <thead>
                    <tr>
                        <th class=""min-width"">
                            <input type=""checkbox"" class=""js-jobs-list-select-all""/>
                        </th>
                        <th class=""min-width"">Id</th>
                        <th class=""min-width"">State</th>
                        <th>Job</th>
                        <th class=""align-right"">Enqueued</th>
                    </tr>
                    </thead>
                    <tbody>
");


            
            #line 135 "..\..\Dashboard\Pages\EnqueuedJobsPage.cshtml"
                     foreach (var job in enqueuedJobs)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <tr class=\"js-jobs-list-row hover ");


            
            #line 137 "..\..\Dashboard\Pages\EnqueuedJobsPage.cshtml"
                                                      Write(!job.Value.InEnqueuedState ? "obsolete-data" : null);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                            <td>\r\n                                <input type" +
"=\"checkbox\" class=\"js-jobs-list-checkbox\" name=\"jobs[]\" value=\"");


            
            #line 139 "..\..\Dashboard\Pages\EnqueuedJobsPage.cshtml"
                                                                                                     Write(job.Key);

            
            #line default
            #line hidden
WriteLiteral("\"/>\r\n                            </td>\r\n                            <td class=\"mi" +
"n-width\">\r\n                                ");


            
            #line 142 "..\..\Dashboard\Pages\EnqueuedJobsPage.cshtml"
                           Write(Html.JobIdLink(job.Key));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 143 "..\..\Dashboard\Pages\EnqueuedJobsPage.cshtml"
                                 if (!job.Value.InEnqueuedState)
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <span title=\"Job\'s state has been changed whi" +
"le fetching data.\" class=\"glyphicon glyphicon-question-sign\"></span>\r\n");


            
            #line 146 "..\..\Dashboard\Pages\EnqueuedJobsPage.cshtml"
                                }

            
            #line default
            #line hidden
WriteLiteral("                            </td>\r\n                            <td class=\"min-wid" +
"th\">\r\n                                ");


            
            #line 149 "..\..\Dashboard\Pages\EnqueuedJobsPage.cshtml"
                           Write(Html.StateLabel(job.Value.State));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </td>\r\n                            <td>\r\n          " +
"                      ");


            
            #line 152 "..\..\Dashboard\Pages\EnqueuedJobsPage.cshtml"
                           Write(Html.JobNameLink(job.Key, job.Value.Job));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </td>\r\n                            <td class=\"align" +
"-right\">\r\n");


            
            #line 155 "..\..\Dashboard\Pages\EnqueuedJobsPage.cshtml"
                                 if (job.Value.EnqueuedAt.HasValue)
                                {
                                    
            
            #line default
            #line hidden
            
            #line 157 "..\..\Dashboard\Pages\EnqueuedJobsPage.cshtml"
                                     if (RelativeTime == true)
                                    {
                                        
            
            #line default
            #line hidden
            
            #line 159 "..\..\Dashboard\Pages\EnqueuedJobsPage.cshtml"
                                   Write(Html.RelativeTime(job.Value.EnqueuedAt.Value));

            
            #line default
            #line hidden
            
            #line 159 "..\..\Dashboard\Pages\EnqueuedJobsPage.cshtml"
                                                                                      ;
                                    }
                                    else
                                    {
                                        
            
            #line default
            #line hidden
            
            #line 163 "..\..\Dashboard\Pages\EnqueuedJobsPage.cshtml"
                                   Write(Html.Raw(job.Value.EnqueuedAt.Value.ToString("dd/MM/yyyy HH:mm")));

            
            #line default
            #line hidden

            
            #line 163 "..\..\Dashboard\Pages\EnqueuedJobsPage.cshtml"
                                                                                                          ;
                                    }
                                }
                                else
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <em>n/a</em>\r\n");


            
            #line 169 "..\..\Dashboard\Pages\EnqueuedJobsPage.cshtml"
                                }

            
            #line default
            #line hidden
WriteLiteral("                            </td>\r\n                        </tr>\r\n");


            
            #line 172 "..\..\Dashboard\Pages\EnqueuedJobsPage.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                    </tbody>\r\n                </table>\r\n\r\n                ");


            
            #line 176 "..\..\Dashboard\Pages\EnqueuedJobsPage.cshtml"
           Write(Html.Paginator(pager));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n");


            
            #line 178 "..\..\Dashboard\Pages\EnqueuedJobsPage.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n</div>");


        }
    }
}
#pragma warning restore 1591
