#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangfire.Dashboard.Pages
{
    
    #line 2 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
    using System;
    
    #line default
    #line hidden
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 3 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
    using Hangfire.Dashboard;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
    using Hangfire.Dashboard.Pages;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
    using Hangfire.States;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class FailedJobsPage : RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");







            
            #line 7 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
  
    Layout = new LayoutPage("Failed Jobs");

    int from, perPage;
    string filterString = Query("filterString");
    string filterMethodString = Query("filterMethodString");
    string startDate = Query("startDate");
    string endDate = Query("endDate");
    string startTime = Query("startTime");
    string endTime = Query("endTime");

    int.TryParse(Query("from"), out from);
    int.TryParse(Query("count"), out perPage);

    var monitor = Storage.GetMonitoringApi();

    var countParameters = new Dictionary<string, string>()
    {
        { "stateName", FailedState.StateName },
        { "filterString", filterString },
        { "filterMethodString", filterMethodString },
        { "startDate", startDate },
        { "endDate", endDate },
        { "startTime", startTime },
        { "endTime", endTime }
    };

    var jobCount = monitor.JobCountByStateName(countParameters);
    var pager = new Pager(from, perPage, jobCount)
    {
        JobsFilterText = filterString,
        JobsFilterMethodText = filterMethodString,
        JobsFilterStartDate = startDate,
        JobsFilterEndDate = endDate,
        JobsFilterStartTime = startTime,
        JobsFilterEndTime = endTime
    };

    var failedJobs = monitor.FailedJobs(pager);


            
            #line default
            #line hidden
WriteLiteral("\r\n<div class=\"row\">\r\n    <div class=\"col-md-3\">\r\n        ");


            
            #line 50 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
   Write(Html.JobsSidebar());

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <div class=\"col-md-9\">\r\n        <h1 class=\"page-header\">Failed " +
"Jobs</h1>\r\n\r\n");


            
            #line 55 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
         if (pager.TotalPageCount == 0)
        {

            
            #line default
            #line hidden
WriteLiteral("            <div class=\"alert alert-success\">\r\n                You have no failed" +
" jobs at the moment.\r\n            </div>\r\n");


            
            #line 60 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
        }
        else
        {

            
            #line default
            #line hidden
WriteLiteral(@"            <div class=""alert alert-warning"">
                <strong>Failed jobs do not become expired</strong> to allow you to re-queue them without any
                time pressure. You should re-queue or delete them manually, or apply <code>AutomaticRetry(OnAttemptsExceeded = AttemptsExceededAction.Delete)</code>
                attribute to delete them automatically.
            </div>
");



WriteLiteral("            <div class=\"js-jobs-list\">\r\n                <div class=\"btn-toolbar b" +
"tn-toolbar-top\">\r\n                    <button class=\"js-jobs-list-command btn bt" +
"n-sm btn-primary\"\r\n                            data-url=\"");


            
            #line 71 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                 Write(Url.To("/jobs/failed/requeue"));

            
            #line default
            #line hidden
WriteLiteral(@"""
                            data-loading-text=""Enqueueing...""
                            disabled=""disabled"">
                        <span class=""glyphicon glyphicon-repeat""></span>
                        Requeue jobs
                    </button>
                    <button class=""js-jobs-list-command btn btn-sm btn-default""
                            data-url=""");


            
            #line 78 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                 Write(Url.To("/jobs/failed/delete"));

            
            #line default
            #line hidden
WriteLiteral(@"""
                            data-loading-text=""Deleting...""
                            data-confirm=""Do you really want to DELETE ALL selected jobs?"">
                        <span class=""glyphicon glyphicon-remove""></span>
                        Delete selected
                    </button>
                    <button data-toggle=""collapse"" data-target=""#advanced-search-bar"" class=""btn btn-sm btn-success"">Advanced Search</button>
                </div>
                <div id=""advanced-search-bar"" class=""collapse well"">
                    <h4 class=""advanced-search-header"">
                        Advanced Search
                    </h4>
                    <div class=""row"">
                        <div class=""col-md-12"">
                            <div class=""form-group"">
                                <input type=""text"" value="""" id=""filterValueString"" class=""form-control"" placeholder=""Search..."" />
                            </div>
                            <div class=""form-group"">
");


            
            #line 96 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                  
                                    var currentDateTime = DateTime.Now.ToString("dd/MM/yyyy HH:mm");
                                

            
            #line default
            #line hidden
WriteLiteral(@"                                <input id=""filterOnDateTime"" name=""filterOnDateTime"" type=""checkbox"" class=""js-jobs-filterOnDateTime-checked"" />
                                <label for=""filterOnDateTime"">Filter on date time</label>

                                <div id=""datetime-filters"" class=""row"">
                                    <div class=""col-xs-6"">
                                        <input type=""text"" value=""");


            
            #line 104 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                                             Write(currentDateTime);

            
            #line default
            #line hidden
WriteLiteral("\" class=\"datetimeselector-start form-control\" id=\"startDateTime\" />\r\n            " +
"                        </div>\r\n                                    <div class=\"" +
"col-xs-6\">\r\n                                        <input type=\"text\" value=\"");


            
            #line 107 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                                             Write(currentDateTime);

            
            #line default
            #line hidden
WriteLiteral(@""" class=""datetimeselector-end form-control"" id=""endDateTime"" />
                                    </div>
                                </div>
                            </div>
                            <div class=""form-group"">
                                <input id=""filterOnMethodName"" name=""filterOnMethodName"" type=""checkbox"" class=""js-jobs-filterOnMethodName-checked"" />
                                <label for=""filterOnMethodName"">Filter on method name</label>
                                <input type=""text"" value="""" id=""filterMethodString"" class=""form-control"" placeholder=""Method name..."" />
                            </div>
                        </div>
                    </div>
                    <div class=""row"">
                        <div class=""col-md-12"">
                            <button class=""js-jobs-filter-command btn btn-sm btn-success""
                                    data-url=""");


            
            #line 121 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                         Write(Url.To("/jobs/failed"));

            
            #line default
            #line hidden
WriteLiteral(@""">
                                <span class=""glyphicon glyphicon-repeat""></span>

                                Filter jobs
                            </button>
                        </div>
                    </div>
                </div>
                ");


            
            #line 129 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
           Write(Html.PerPageSelector(pager));

            
            #line default
            #line hidden
WriteLiteral(@"
                <table class=""table"">
                    <thead>
                        <tr>
                            <th class=""min-width"">
                                <input type=""checkbox"" class=""js-jobs-list-select-all"" />
                            </th>
                            <th class=""min-width"">Id</th>
                            <th>Failed</th>
                            <th>Job</th>
                        </tr>
                    </thead>
                    <tbody>
");


            
            #line 142 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                           var index = 0; 

            
            #line default
            #line hidden

            
            #line 143 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                         foreach (var job in failedJobs)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <tr class=\"js-jobs-list-row ");


            
            #line 145 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                                    Write(!job.Value.InFailedState ? "obsolete-data" : null);

            
            #line default
            #line hidden
WriteLiteral(" ");


            
            #line 145 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                                                                                         Write(job.Value.InFailedState ? "hover" : null);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                                <td rowspan=\"");


            
            #line 146 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                         Write(job.Value.InFailedState ? "2" : "1");

            
            #line default
            #line hidden
WriteLiteral("\">\r\n");


            
            #line 147 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                     if (job.Value.InFailedState)
                                    {

            
            #line default
            #line hidden
WriteLiteral("                                        <input type=\"checkbox\" class=\"js-jobs-lis" +
"t-checkbox\" name=\"jobs[]\" value=\"");


            
            #line 149 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                                                                                             Write(job.Key);

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n");


            
            #line 150 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                    }

            
            #line default
            #line hidden
WriteLiteral("                                </td>\r\n                                <td class=" +
"\"min-width\" rowspan=\"");


            
            #line 152 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                                           Write(job.Value.InFailedState ? "2" : "1");

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                                    ");


            
            #line 153 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                               Write(Html.JobIdLink(job.Key));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 154 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                     if (!job.Value.InFailedState)
                                    {

            
            #line default
            #line hidden
WriteLiteral("                                        <span title=\"Job\'s state has been changed" +
" while fetching data.\" class=\"glyphicon glyphicon-question-sign\"></span>\r\n");


            
            #line 157 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                    }

            
            #line default
            #line hidden
WriteLiteral("                                </td>\r\n                                <td class=" +
"\"min-width\">\r\n");


            
            #line 160 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                     if (job.Value.FailedAt.HasValue)
                                    {
                                        
            
            #line default
            #line hidden
            
            #line 162 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                   Write(Html.Raw(job.Value.FailedAt.Value.ToString("dd/MM/yyyy HH:mm")));

            
            #line default
            #line hidden
            
            #line 162 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                                                                                        ;
                                    }

            
            #line default
            #line hidden
WriteLiteral("                                </td>\r\n                                <td>\r\n    " +
"                                <div>\r\n                                        ");


            
            #line 167 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                   Write(Html.JobNameLink(job.Key, job.Value.Job));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </div>\r\n");


            
            #line 169 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                     if (!String.IsNullOrEmpty(job.Value.ExceptionMessage))
                                    {

            
            #line default
            #line hidden
WriteLiteral("                                        <div style=\"color: #888;\">\r\n             " +
"                               ");


            
            #line 172 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                       Write(job.Value.Reason);

            
            #line default
            #line hidden
WriteLiteral(" <a class=\"expander\" href=\"#\">");


            
            #line 172 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                                                                       Write(index == 0 ? "Less details..." : "More details...");

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n                                        </div>\r\n");


            
            #line 174 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                    }

            
            #line default
            #line hidden
WriteLiteral("                                </td>\r\n                            </tr>\r\n");


            
            #line 177 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                            if (job.Value.InFailedState)
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <tr>\r\n                                    <td col" +
"span=\"2\" class=\"failed-job-details\">\r\n                                        <d" +
"iv class=\"expandable\" style=\"");


            
            #line 181 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                                                   Write(index++ == 0 ? "display: block;" : null);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                                            <h4>");


            
            #line 182 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                           Write(job.Value.ExceptionType);

            
            #line default
            #line hidden
WriteLiteral("</h4>\r\n                                            <p>\r\n                         " +
"                       ");


            
            #line 184 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                           Write(job.Value.ExceptionMessage);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                            </p>\r\n\r\n");


            
            #line 187 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                             if (!String.IsNullOrEmpty(job.Value.ExceptionDetails))
                                            {

            
            #line default
            #line hidden
WriteLiteral("                                                <pre class=\"stack-trace\"><code>");


            
            #line 189 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                                                          Write(Html.StackTrace(job.Value.ExceptionDetails));

            
            #line default
            #line hidden
WriteLiteral("</code></pre>\r\n");


            
            #line 190 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                                            }

            
            #line default
            #line hidden
WriteLiteral("                                        </div>\r\n                                 " +
"   </td>\r\n                                </tr>\r\n");


            
            #line 194 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                            }
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </tbody>\r\n                </table>\r\n                ");


            
            #line 198 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
           Write(Html.Paginator(pager));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n");


            
            #line 200 "..\..\Dashboard\Pages\FailedJobsPage.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n</div>");


        }
    }
}
#pragma warning restore 1591
